/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ActionEnum = {

    /**
     * TODO: Write general description for this element
     */
    MOVE_TO_CART: 'MoveToCart',

    /**
     * TODO: Write general description for this element
     */
    SAVE_FOR_LATER: 'SaveForLater',

};

module.exports = ActionEnum;
