/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const AudienceRatingEnum = {

    /**
     * TODO: Write general description for this element
     */
    G: 'G',

    /**
     * TODO: Write general description for this element
     */
    PG: 'PG',

    /**
     * TODO: Write general description for this element
     */
    PG_13: 'PG-13',

    /**
     * TODO: Write general description for this element
     */
    R: 'R',

    /**
     * TODO: Write general description for this element
     */
    NC_17: 'NC-17',

    /**
     * TODO: Write general description for this element
     */
    NR: 'NR',

    /**
     * TODO: Write general description for this element
     */
    UNRATED: 'Unrated',

    /**
     * TODO: Write general description for this element
     */
    ENUM_6: '6',

    /**
     * TODO: Write general description for this element
     */
    ENUM_12: '12',

    /**
     * TODO: Write general description for this element
     */
    ENUM_16: '16',

    /**
     * TODO: Write general description for this element
     */
    ENUM_18: '18',

    /**
     * TODO: Write general description for this element
     */
    FAMILY_VIEWING: 'FamilyViewing',

};

module.exports = AudienceRatingEnum;
