/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const AvailabilityEnum = {

    /**
     * TODO: Write general description for this element
     */
    AVAILABLE: 'Available',

};

module.exports = AvailabilityEnum;
