/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AvailabilityAttributes
 */
class AvailabilityAttributes extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.availabilityType =
          this.constructor.getValue(obj.availabilityType
     || obj.AvailabilityType);
        this.isPreorder = this.constructor.getValue(obj.isPreorder || obj.IsPreorder);
        this.minimumHours = this.constructor.getValue(obj.minimumHours || obj.MinimumHours);
        this.maximumHours = this.constructor.getValue(obj.maximumHours || obj.MaximumHours);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'availabilityType', realName: 'AvailabilityType' },
            { name: 'isPreorder', realName: 'IsPreorder' },
            { name: 'minimumHours', realName: 'MinimumHours' },
            { name: 'maximumHours', realName: 'MaximumHours' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AvailabilityAttributes;
