/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Bin
 */
class Bin extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.binName = this.constructor.getValue(obj.binName || obj.BinName);
        this.binItemCount = this.constructor.getValue(obj.binItemCount || obj.BinItemCount);
        this.binParameter = this.constructor.getValue(obj.binParameter || obj.BinParameter);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'binName', realName: 'BinName' },
            { name: 'binItemCount', realName: 'BinItemCount' },
            { name: 'binParameter', realName: 'BinParameter', array: true, type: 'BinParameter' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Bin;
