/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CollectionSummary
 */
class CollectionSummary extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.lowestListPrice =
          this.constructor.getValue(obj.lowestListPrice
     || obj.LowestListPrice);
        this.highestListPrice =
          this.constructor.getValue(obj.highestListPrice
     || obj.HighestListPrice);
        this.lowestSalePrice =
          this.constructor.getValue(obj.lowestSalePrice
     || obj.LowestSalePrice);
        this.highestSalePrice =
          this.constructor.getValue(obj.highestSalePrice
     || obj.HighestSalePrice);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'lowestListPrice', realName: 'LowestListPrice', type: 'Price' },
            { name: 'highestListPrice', realName: 'HighestListPrice', type: 'Price' },
            { name: 'lowestSalePrice', realName: 'LowestSalePrice', type: 'Price' },
            { name: 'highestSalePrice', realName: 'HighestSalePrice', type: 'Price' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CollectionSummary;
