/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Collection
 */
class Collection extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.collectionSummary =
          this.constructor.getValue(obj.collectionSummary
     || obj.CollectionSummary);
        this.collectionParent =
          this.constructor.getValue(obj.collectionParent
     || obj.CollectionParent);
        this.collectionItem = this.constructor.getValue(obj.collectionItem || obj.CollectionItem);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'collectionSummary', realName: 'CollectionSummary', type: 'CollectionSummary' },
            { name: 'collectionParent', realName: 'CollectionParent', type: 'CollectionParent' },
            {
                name: 'collectionItem',
                realName: 'CollectionItem',
                array: true,
                type: 'CollectionItem',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Collection;
