/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ConditionEnum = {

    /**
     * TODO: Write general description for this element
     */
    ALL: 'All',

    /**
     * TODO: Write general description for this element
     */
    NEW: 'New',

    /**
     * TODO: Write general description for this element
     */
    USED: 'Used',

    /**
     * TODO: Write general description for this element
     */
    COLLECTIBLE: 'Collectible',

    /**
     * TODO: Write general description for this element
     */
    REFURBISHED: 'Refurbished',

};

module.exports = ConditionEnum;
