/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EditorialReview
 */
class EditorialReview extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.source = this.constructor.getValue(obj.source || obj.Source);
        this.content = this.constructor.getValue(obj.content || obj.Content);
        this.isLinkSuppressed =
          this.constructor.getValue(obj.isLinkSuppressed
     || obj.IsLinkSuppressed);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'source', realName: 'Source' },
            { name: 'content', realName: 'Content' },
            { name: 'isLinkSuppressed', realName: 'IsLinkSuppressed' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EditorialReview;
