/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const IdTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    ASIN: 'ASIN',

    /**
     * TODO: Write general description for this element
     */
    UPC: 'UPC',

    /**
     * TODO: Write general description for this element
     */
    SKU: 'SKU',

    /**
     * TODO: Write general description for this element
     */
    EAN: 'EAN',

    /**
     * TODO: Write general description for this element
     */
    ISBN: 'ISBN',

};

module.exports = IdTypeEnum;
