/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Image
 */
class Image extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.uRL = this.constructor.getValue(obj.uRL || obj.URL);
        this.height = this.constructor.getValue(obj.height || obj.Height);
        this.width = this.constructor.getValue(obj.width || obj.Width);
        this.isVerified = this.constructor.getValue(obj.isVerified || obj.IsVerified);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'uRL', realName: 'URL' },
            { name: 'height', realName: 'Height', type: 'DecimalWithUnits' },
            { name: 'width', realName: 'Width', type: 'DecimalWithUnits' },
            { name: 'isVerified', realName: 'IsVerified' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Image;
