/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Items134
 */
class Items134 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.request = this.constructor.getValue(obj.request || obj.Request);
        this.correctedQuery = this.constructor.getValue(obj.correctedQuery || obj.CorrectedQuery);
        this.qid = this.constructor.getValue(obj.qid || obj.Qid);
        this.engineQuery = this.constructor.getValue(obj.engineQuery || obj.EngineQuery);
        this.totalResults = this.constructor.getValue(obj.totalResults || obj.TotalResults);
        this.totalPages = this.constructor.getValue(obj.totalPages || obj.TotalPages);
        this.moreSearchResultsUrl =
          this.constructor.getValue(obj.moreSearchResultsUrl
     || obj.MoreSearchResultsUrl);
        this.searchResultsMap =
          this.constructor.getValue(obj.searchResultsMap
     || obj.SearchResultsMap);
        this.item = this.constructor.getValue(obj.item || obj.Item);
        this.searchBinSets = this.constructor.getValue(obj.searchBinSets || obj.SearchBinSets);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'request', realName: 'Request', type: 'Request' },
            { name: 'correctedQuery', realName: 'CorrectedQuery', type: 'CorrectedQuery' },
            { name: 'qid', realName: 'Qid' },
            { name: 'engineQuery', realName: 'EngineQuery' },
            { name: 'totalResults', realName: 'TotalResults' },
            { name: 'totalPages', realName: 'TotalPages' },
            { name: 'moreSearchResultsUrl', realName: 'MoreSearchResultsUrl' },
            { name: 'searchResultsMap', realName: 'SearchResultsMap', type: 'SearchResultsMap' },
            { name: 'item', realName: 'Item', array: true, type: 'Item133' },
            { name: 'searchBinSets', realName: 'SearchBinSets', type: 'SearchBinSets' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Items134;
