/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Item
 */
class Item extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.aSIN = this.constructor.getValue(obj.aSIN || obj.ASIN);
        this.offerListingId = this.constructor.getValue(obj.offerListingId || obj.OfferListingId);
        this.quantity = this.constructor.getValue(obj.quantity || obj.Quantity);
        this.associateTag = this.constructor.getValue(obj.associateTag || obj.AssociateTag);
        this.listItemId = this.constructor.getValue(obj.listItemId || obj.ListItemId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'aSIN', realName: 'ASIN' },
            { name: 'offerListingId', realName: 'OfferListingId' },
            { name: 'quantity', realName: 'Quantity' },
            { name: 'associateTag', realName: 'AssociateTag' },
            { name: 'listItemId', realName: 'ListItemId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Item;
