/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of PackageDimensions
 */
class PackageDimensions extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.height = this.constructor.getValue(obj.height || obj.Height);
        this.length = this.constructor.getValue(obj.length || obj.Length);
        this.weight = this.constructor.getValue(obj.weight || obj.Weight);
        this.width = this.constructor.getValue(obj.width || obj.Width);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'height', realName: 'Height', type: 'DecimalWithUnits' },
            { name: 'length', realName: 'Length', type: 'DecimalWithUnits' },
            { name: 'weight', realName: 'Weight', type: 'DecimalWithUnits' },
            { name: 'width', realName: 'Width', type: 'DecimalWithUnits' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = PackageDimensions;
