/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const PositiveIntegerOrAllEnum = {

    /**
     * TODO: Write general description for this element
     */
    ALL: 'All',

};

module.exports = PositiveIntegerOrAllEnum;
