/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const RelationshipEnum = {

    /**
     * TODO: Write general description for this element
     */
    PARENTS: 'Parents',

    /**
     * TODO: Write general description for this element
     */
    CHILDREN: 'Children',

};

module.exports = RelationshipEnum;
