/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of RentalListing
 */
class RentalListing extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.price = this.constructor.getValue(obj.price || obj.Price);
        this.period = this.constructor.getValue(obj.period || obj.Period);
        this.isFulfilledByAmazon =
          this.constructor.getValue(obj.isFulfilledByAmazon
     || obj.IsFulfilledByAmazon);
        this.disclaimer = this.constructor.getValue(obj.disclaimer || obj.Disclaimer);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'price', realName: 'Price', type: 'Price' },
            { name: 'period', realName: 'Period', type: 'NonNegativeIntegerWithUnits' },
            { name: 'isFulfilledByAmazon', realName: 'IsFulfilledByAmazon' },
            { name: 'disclaimer', realName: 'Disclaimer' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = RentalListing;
