/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const SimilarityTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    INTERSECTION: 'Intersection',

    /**
     * TODO: Write general description for this element
     */
    RANDOM: 'Random',

};

module.exports = SimilarityTypeEnum;
