/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Summary
 */
class Summary extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.promotionId = this.constructor.getValue(obj.promotionId || obj.PromotionId);
        this.message = this.constructor.getValue(obj.message || obj.Message);
        this.category = this.constructor.getValue(obj.category || obj.Category);
        this.startDate = this.constructor.getValue(obj.startDate || obj.StartDate);
        this.endDate = this.constructor.getValue(obj.endDate || obj.EndDate);
        this.eligibilityRequirementDescription =
          this.constructor.getValue(obj.eligibilityRequirementDescription
     || obj.EligibilityRequirementDescription);
        this.benefitDescription =
          this.constructor.getValue(obj.benefitDescription
     || obj.BenefitDescription);
        this.termsAndConditions =
          this.constructor.getValue(obj.termsAndConditions
     || obj.TermsAndConditions);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'promotionId', realName: 'PromotionId' },
            { name: 'message', realName: 'Message' },
            { name: 'category', realName: 'Category' },
            { name: 'startDate', realName: 'StartDate' },
            { name: 'endDate', realName: 'EndDate' },
            {
                name: 'eligibilityRequirementDescription',
                realName: 'EligibilityRequirementDescription',
            },
            { name: 'benefitDescription', realName: 'BenefitDescription' },
            { name: 'termsAndConditions', realName: 'TermsAndConditions' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Summary;
