/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Variations
 */
class Variations extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.totalVariations =
          this.constructor.getValue(obj.totalVariations
     || obj.TotalVariations);
        this.totalVariationPages =
          this.constructor.getValue(obj.totalVariationPages
     || obj.TotalVariationPages);
        this.variationDimensions =
          this.constructor.getValue(obj.variationDimensions
     || obj.VariationDimensions);
        this.item = this.constructor.getValue(obj.item || obj.Item);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'totalVariations', realName: 'TotalVariations' },
            { name: 'totalVariationPages', realName: 'TotalVariationPages' },
            {
                name: 'variationDimensions',
                realName: 'VariationDimensions',
                type: 'VariationDimensions',
            },
            { name: 'item', realName: 'Item', array: true, type: 'Item' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Variations;
