/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const servers = require('./Servers');
const environments = require('./Environments');
const apiHelper = require('./APIHelper');

const environmentsMap = [];

environmentsMap[environments.PRODUCTION] = [];

environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT] =
    'https://webservices.amazon.com/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_CA] =
    'https://webservices.amazon.ca/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_CN] =
    'https://webservices.amazon.cn/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_DE] =
    'https://webservices.amazon.de/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_ES] =
    'https://webservices.amazon.es/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_FR] =
    'https://webservices.amazon.fr/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_IN] =
    'https://webservices.amazon.in/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_IT] =
    'https://webservices.amazon.it/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_JP] =
    'https://webservices.amazon.co.jp/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_UK] =
    'https://webservices.amazon.co.uk/onca/soap?Service=AWSECommerceService';
environmentsMap[environments.PRODUCTION][servers.AWSE_COMMERCE_SERVICE_PORT_US] =
    'https://webservices.amazon.com/onca/soap?Service=AWSECommerceService';

const Configuration = {
    /**
     * Current API environment
     * @type {string}
     */
    currentEnvironment: environments.PRODUCTION,

    /**
     * Get base URI for a server in the current API environment
     * @param  {string|null} server Server name
     * @return {string}             Base URI for server
     */
    getBaseUri(server) {
        const url = environmentsMap[this.currentEnvironment][server || servers.AWSE_COMMERCE_SERVICE_PORT];
        const urlParams = {
        };
        return apiHelper.appendUrlWithTemplateParameters(url, urlParams);
    },
};

module.exports = Configuration;
