/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BinParameter = require('../lib/Models/BinParameter');
const Bin = require('../lib/Models/Bin');
const SearchBinSet = require('../lib/Models/SearchBinSet');
const MetaData = require('../lib/Models/MetaData');
const CartCreateRequest = require('../lib/Models/CartCreateRequest');
const Item34 = require('../lib/Models/Item34');
const BrowseNodeLookupRequest = require('../lib/Models/BrowseNodeLookupRequest');
const Header = require('../lib/Models/Header');
const Argument = require('../lib/Models/Argument');
const MError = require('../lib/Models/MError');
const CartCreateRequest55 = require('../lib/Models/CartCreateRequest55');
const CorrectedQuery = require('../lib/Models/CorrectedQuery');
const ItemLink = require('../lib/Models/ItemLink');
const Language = require('../lib/Models/Language');
const Price = require('../lib/Models/Price');
const VariationAttribute = require('../lib/Models/VariationAttribute');
const CollectionParent = require('../lib/Models/CollectionParent');
const CollectionItem = require('../lib/Models/CollectionItem');
const Collection = require('../lib/Models/Collection');
const LoyaltyPoints = require('../lib/Models/LoyaltyPoints');
const RentalOffer = require('../lib/Models/RentalOffer');
const CustomerReviews = require('../lib/Models/CustomerReviews');
const EditorialReview = require('../lib/Models/EditorialReview');
const SimilarProduct = require('../lib/Models/SimilarProduct');
const Accessory = require('../lib/Models/Accessory');
const Disc = require('../lib/Models/Disc');
const Property = require('../lib/Models/Property');
const TopSeller = require('../lib/Models/TopSeller');
const NewRelease = require('../lib/Models/NewRelease');
const TopItemSet = require('../lib/Models/TopItemSet');
const BrowseNodes = require('../lib/Models/BrowseNodes');
const AlternateVersion = require('../lib/Models/AlternateVersion');
const ItemSearchResponse = require('../lib/Models/ItemSearchResponse');
const ItemLookupResponse = require('../lib/Models/ItemLookupResponse');
const SimilarityLookupResponse = require('../lib/Models/SimilarityLookupResponse');
const KeyValuePair = require('../lib/Models/KeyValuePair');
const CartItems = require('../lib/Models/CartItems');
const SavedForLaterItems = require('../lib/Models/SavedForLaterItems');
const SimilarViewedProduct = require('../lib/Models/SimilarViewedProduct');
const OtherCategoriesSimilarProduct = require('../lib/Models/OtherCategoriesSimilarProduct');
const CartGetResponse = require('../lib/Models/CartGetResponse');
const CartAddResponse = require('../lib/Models/CartAddResponse');
const CartCreateResponse = require('../lib/Models/CartCreateResponse');
const CartModifyResponse = require('../lib/Models/CartModifyResponse');
const CartClearResponse = require('../lib/Models/CartClearResponse');
const BrowseNodes243 = require('../lib/Models/BrowseNodes243');
const BrowseNodeLookupResponse = require('../lib/Models/BrowseNodeLookupResponse');
const SearchBinSets = require('../lib/Models/SearchBinSets');
const ItemSearchRequest = require('../lib/Models/ItemSearchRequest');
const ItemSearch = require('../lib/Models/ItemSearch');
const ItemLookupRequest = require('../lib/Models/ItemLookupRequest');
const ItemLookup = require('../lib/Models/ItemLookup');
const SimilarityLookupRequest = require('../lib/Models/SimilarityLookupRequest');
const SimilarityLookup = require('../lib/Models/SimilarityLookup');
const CartGetRequest = require('../lib/Models/CartGetRequest');
const CartGet = require('../lib/Models/CartGet');
const Item = require('../lib/Models/Item');
const Items = require('../lib/Models/Items');
const CartAddRequest = require('../lib/Models/CartAddRequest');
const CartAdd = require('../lib/Models/CartAdd');
const Item23 = require('../lib/Models/Item23');
const Items24 = require('../lib/Models/Items24');
const CartCreate = require('../lib/Models/CartCreate');
const Items35 = require('../lib/Models/Items35');
const CartModifyRequest = require('../lib/Models/CartModifyRequest');
const CartModify = require('../lib/Models/CartModify');
const CartClearRequest = require('../lib/Models/CartClearRequest');
const CartClear = require('../lib/Models/CartClear');
const BrowseNodeLookup = require('../lib/Models/BrowseNodeLookup');
const HTTPHeaders = require('../lib/Models/HTTPHeaders');
const Arguments = require('../lib/Models/Arguments');
const Errors = require('../lib/Models/Errors');
const OperationRequest = require('../lib/Models/OperationRequest');
const CartModifyRequest56 = require('../lib/Models/CartModifyRequest56');
const Request = require('../lib/Models/Request');
const SearchIndex = require('../lib/Models/SearchIndex');
const SearchResultsMap = require('../lib/Models/SearchResultsMap');
const ItemLinks = require('../lib/Models/ItemLinks');
const DecimalWithUnits = require('../lib/Models/DecimalWithUnits');
const Image = require('../lib/Models/Image');
const ImageSet = require('../lib/Models/ImageSet');
const ImageSets = require('../lib/Models/ImageSets');
const CatalogNumberList = require('../lib/Models/CatalogNumberList');
const Creator = require('../lib/Models/Creator');
const EANList = require('../lib/Models/EANList');
const ItemDimensions = require('../lib/Models/ItemDimensions');
const Languages = require('../lib/Models/Languages');
const PackageDimensions = require('../lib/Models/PackageDimensions');
const NonNegativeIntegerWithUnits = require('../lib/Models/NonNegativeIntegerWithUnits');
const UPCList = require('../lib/Models/UPCList');
const ItemAttributes = require('../lib/Models/ItemAttributes');
const VariationAttributes = require('../lib/Models/VariationAttributes');
const RelatedItem = require('../lib/Models/RelatedItem');
const RelatedItems = require('../lib/Models/RelatedItems');
const CollectionSummary = require('../lib/Models/CollectionSummary');
const Collections = require('../lib/Models/Collections');
const Subjects = require('../lib/Models/Subjects');
const OfferSummary = require('../lib/Models/OfferSummary');
const Merchant = require('../lib/Models/Merchant');
const OfferAttributes = require('../lib/Models/OfferAttributes');
const AvailabilityAttributes = require('../lib/Models/AvailabilityAttributes');
const OfferListing = require('../lib/Models/OfferListing');
const Summary = require('../lib/Models/Summary');
const Promotion = require('../lib/Models/Promotion');
const Promotions = require('../lib/Models/Promotions');
const Offer = require('../lib/Models/Offer');
const Offers = require('../lib/Models/Offers');
const RentalListing = require('../lib/Models/RentalListing');
const RentalOffers = require('../lib/Models/RentalOffers');
const VariationSummary = require('../lib/Models/VariationSummary');
const VariationDimensions = require('../lib/Models/VariationDimensions');
const Variations = require('../lib/Models/Variations');
const EditorialReviews = require('../lib/Models/EditorialReviews');
const SimilarProducts = require('../lib/Models/SimilarProducts');
const Accessories = require('../lib/Models/Accessories');
const Track = require('../lib/Models/Track');
const Tracks = require('../lib/Models/Tracks');
const Properties = require('../lib/Models/Properties');
const Children = require('../lib/Models/Children');
const Ancestors = require('../lib/Models/Ancestors');
const TopSellers = require('../lib/Models/TopSellers');
const NewReleases = require('../lib/Models/NewReleases');
const TopItem = require('../lib/Models/TopItem');
const BrowseNode = require('../lib/Models/BrowseNode');
const AlternateVersions = require('../lib/Models/AlternateVersions');
const Item133 = require('../lib/Models/Item133');
const Items134 = require('../lib/Models/Items134');
const Request162 = require('../lib/Models/Request162');
const MetaData164 = require('../lib/Models/MetaData164');
const CartItem = require('../lib/Models/CartItem');
const SimilarViewedProducts = require('../lib/Models/SimilarViewedProducts');
const OtherCategoriesSimilarProducts = require('../lib/Models/OtherCategoriesSimilarProducts');
const Cart = require('../lib/Models/Cart');
const Item253 = require('../lib/Models/Item253');
const Items254 = require('../lib/Models/Items254');
const RelatedItem264 = require('../lib/Models/RelatedItem264');
const RelatedItems265 = require('../lib/Models/RelatedItems265');
const Variations267 = require('../lib/Models/Variations267');
const StringWithUnits = require('../lib/Models/StringWithUnits');
const ItemSearchResponseMsg = require('../lib/Models/ItemSearchResponseMsg');
const ItemLookupResponseMsg = require('../lib/Models/ItemLookupResponseMsg');
const BrowseNodeLookupResponseMsg = require('../lib/Models/BrowseNodeLookupResponseMsg');
const SimilarityLookupResponseMsg = require('../lib/Models/SimilarityLookupResponseMsg');
const CartGetResponseMsg = require('../lib/Models/CartGetResponseMsg');
const CartAddResponseMsg = require('../lib/Models/CartAddResponseMsg');
const CartCreateResponseMsg = require('../lib/Models/CartCreateResponseMsg');
const CartModifyResponseMsg = require('../lib/Models/CartModifyResponseMsg');
const CartClearResponseMsg = require('../lib/Models/CartClearResponseMsg');
const ItemSearchRequestMsg = require('../lib/Models/ItemSearchRequestMsg');
const ItemLookupRequestMsg = require('../lib/Models/ItemLookupRequestMsg');
const BrowseNodeLookupRequestMsg = require('../lib/Models/BrowseNodeLookupRequestMsg');
const SimilarityLookupRequestMsg = require('../lib/Models/SimilarityLookupRequestMsg');
const CartGetRequestMsg = require('../lib/Models/CartGetRequestMsg');
const CartAddRequestMsg = require('../lib/Models/CartAddRequestMsg');
const CartCreateRequestMsg = require('../lib/Models/CartCreateRequestMsg');
const CartModifyRequestMsg = require('../lib/Models/CartModifyRequestMsg');
const CartClearRequestMsg = require('../lib/Models/CartClearRequestMsg');

const classMap = {
    BinParameter,
    Bin,
    SearchBinSet,
    MetaData,
    CartCreateRequest,
    Item34,
    BrowseNodeLookupRequest,
    Header,
    Argument,
    MError,
    CartCreateRequest55,
    CorrectedQuery,
    ItemLink,
    Language,
    Price,
    VariationAttribute,
    CollectionParent,
    CollectionItem,
    Collection,
    LoyaltyPoints,
    RentalOffer,
    CustomerReviews,
    EditorialReview,
    SimilarProduct,
    Accessory,
    Disc,
    Property,
    TopSeller,
    NewRelease,
    TopItemSet,
    BrowseNodes,
    AlternateVersion,
    ItemSearchResponse,
    ItemLookupResponse,
    SimilarityLookupResponse,
    KeyValuePair,
    CartItems,
    SavedForLaterItems,
    SimilarViewedProduct,
    OtherCategoriesSimilarProduct,
    CartGetResponse,
    CartAddResponse,
    CartCreateResponse,
    CartModifyResponse,
    CartClearResponse,
    BrowseNodes243,
    BrowseNodeLookupResponse,
    SearchBinSets,
    ItemSearchRequest,
    ItemSearch,
    ItemLookupRequest,
    ItemLookup,
    SimilarityLookupRequest,
    SimilarityLookup,
    CartGetRequest,
    CartGet,
    Item,
    Items,
    CartAddRequest,
    CartAdd,
    Item23,
    Items24,
    CartCreate,
    Items35,
    CartModifyRequest,
    CartModify,
    CartClearRequest,
    CartClear,
    BrowseNodeLookup,
    HTTPHeaders,
    Arguments,
    Errors,
    OperationRequest,
    CartModifyRequest56,
    Request,
    SearchIndex,
    SearchResultsMap,
    ItemLinks,
    DecimalWithUnits,
    Image,
    ImageSet,
    ImageSets,
    CatalogNumberList,
    Creator,
    EANList,
    ItemDimensions,
    Languages,
    PackageDimensions,
    NonNegativeIntegerWithUnits,
    UPCList,
    ItemAttributes,
    VariationAttributes,
    RelatedItem,
    RelatedItems,
    CollectionSummary,
    Collections,
    Subjects,
    OfferSummary,
    Merchant,
    OfferAttributes,
    AvailabilityAttributes,
    OfferListing,
    Summary,
    Promotion,
    Promotions,
    Offer,
    Offers,
    RentalListing,
    RentalOffers,
    VariationSummary,
    VariationDimensions,
    Variations,
    EditorialReviews,
    SimilarProducts,
    Accessories,
    Track,
    Tracks,
    Properties,
    Children,
    Ancestors,
    TopSellers,
    NewReleases,
    TopItem,
    BrowseNode,
    AlternateVersions,
    Item133,
    Items134,
    Request162,
    MetaData164,
    CartItem,
    SimilarViewedProducts,
    OtherCategoriesSimilarProducts,
    Cart,
    Item253,
    Items254,
    RelatedItem264,
    RelatedItems265,
    Variations267,
    StringWithUnits,
    ItemSearchResponseMsg,
    ItemLookupResponseMsg,
    BrowseNodeLookupResponseMsg,
    SimilarityLookupResponseMsg,
    CartGetResponseMsg,
    CartAddResponseMsg,
    CartCreateResponseMsg,
    CartModifyResponseMsg,
    CartClearResponseMsg,
    ItemSearchRequestMsg,
    ItemLookupRequestMsg,
    BrowseNodeLookupRequestMsg,
    SimilarityLookupRequestMsg,
    CartGetRequestMsg,
    CartAddRequestMsg,
    CartCreateRequestMsg,
    CartModifyRequestMsg,
    CartClearRequestMsg,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
