/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT: 'AWSECommerceServicePort',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_CA: 'AWSECommerceServicePortCA',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_CN: 'AWSECommerceServicePortCN',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_DE: 'AWSECommerceServicePortDE',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_ES: 'AWSECommerceServicePortES',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_FR: 'AWSECommerceServicePortFR',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_IN: 'AWSECommerceServicePortIN',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_IT: 'AWSECommerceServicePortIT',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_JP: 'AWSECommerceServicePortJP',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_UK: 'AWSECommerceServicePortUK',

    /**
     * TODO: Write general description for this element
     */
    AWSE_COMMERCE_SERVICE_PORT_US: 'AWSECommerceServicePortUS',

};

module.exports = Servers;
