/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Add 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5253445093385162559L;
    private Integer a;
    private Integer b;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("a")
    public Integer getA ( ) { 
        return this.a;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("a")
    public void setA (Integer value) { 
        this.a = value;
        notifyObservers(this.a);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("b")
    public Integer getB ( ) { 
        return this.b;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("b")
    public void setB (Integer value) { 
        this.b = value;
        notifyObservers(this.b);
    }
 
}
 