/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AddResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5757617384096566878L;
    private Integer result;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("result")
    public Integer getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("result")
    public void setResult (Integer value) { 
        this.result = value;
        notifyObservers(this.result);
    }
 
}
 