/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ICalculatorAddInputMessage 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5680546735764740583L;
    private Add parameters;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parameters")
    public Add getParameters ( ) { 
        return this.parameters;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parameters")
    public void setParameters (Add value) { 
        this.parameters = value;
        notifyObservers(this.parameters);
    }
 
}
 