/**
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ICalculatorAddOutputMessage
 *
 * @constructor
 */
angular.module('CalculatorServiceLib')
    .factory('ICalculatorAddOutputMessage', ['BaseModel', ICalculatorAddOutputMessageModel]);

    function ICalculatorAddOutputMessageModel(BaseModel) {
        var ICalculatorAddOutputMessage = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.parameters = this.getValue(obj.parameters);
        };

        ICalculatorAddOutputMessage.prototype = new BaseModel();
        ICalculatorAddOutputMessage.prototype.constructor = ICalculatorAddOutputMessage;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ICalculatorAddOutputMessage.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'parameters', realName: 'parameters', type: 'AddResponse' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ICalculatorAddOutputMessage.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {AddResponse}
         */
        ICalculatorAddOutputMessage.prototype.getParameters = function () {
            return this.parameters;
        };
    
        /**
         * Setter for Parameters
         * 
         * @param {AddResponse} value 
         */
        ICalculatorAddOutputMessage.prototype.setParameters = function (value) {
            this.parameters = value;
        };
    
        return ICalculatorAddOutputMessage;
    }

}(angular));
