/**
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ICalculatorAddInputMessage
 *
 * @constructor
 */
angular.module('CalculatorServiceLib')
    .factory('ICalculatorAddInputMessage', ['BaseModel', ICalculatorAddInputMessageModel]);

    function ICalculatorAddInputMessageModel(BaseModel) {
        var ICalculatorAddInputMessage = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.parameters = this.getValue(obj.parameters);
        };

        ICalculatorAddInputMessage.prototype = new BaseModel();
        ICalculatorAddInputMessage.prototype.constructor = ICalculatorAddInputMessage;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ICalculatorAddInputMessage.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'parameters', realName: 'parameters', type: 'Add' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ICalculatorAddInputMessage.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Add}
         */
        ICalculatorAddInputMessage.prototype.getParameters = function () {
            return this.parameters;
        };
    
        /**
         * Setter for Parameters
         * 
         * @param {Add} value 
         */
        ICalculatorAddInputMessage.prototype.setParameters = function (value) {
            this.parameters = value;
        };
    
        return ICalculatorAddInputMessage;
    }

}(angular));
