/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example;

import org.example.controllers.*;
import org.example.http.client.HttpClient;

public class CalculatorServiceClient {
    /**
     * Singleton access to DefaultBindingICalculator controller
     * @return	Returns the DefaultBindingICalculatorController instance 
     */
    public DefaultBindingICalculatorController getDefaultBindingICalculator() {
        return DefaultBindingICalculatorController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public CalculatorServiceClient() {
    }

}