# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CalculatorService
  #  calculator_service client class.
  class CalculatorServiceClient
    # Singleton access to default_binding_i_calculator controller.
    # @return [DefaultBindingICalculatorController] Returns the controller instance.
    def default_binding_i_calculator
      DefaultBindingICalculatorController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
