# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CalculatorService
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # Set the array parameter serialization method.
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    @array_serialization = 'indexed'

    # An enum for SDK environments.
    class Environment
      ENVIRONMENT = [PRODUCTION = 0, TESTING = 1].freeze
    end

    # An enum for API servers.
    class Server
      SERVER = [ICALCULATOR = 0].freeze
    end

    # The environment in which the SDK is running.
    @environment = Environment::PRODUCTION

    # All the environments the SDK can run in.
    @environments = {
      Environment::PRODUCTION => {
        Server::ICALCULATOR => 'http://Example.org/ICalculator'
      },
      Environment::TESTING => {
        Server::ICALCULATOR => 'sd'
      }
    }

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def self.get_base_uri(server = Server::ICALCULATOR)
      environments[environment][server]
    end

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization
      attr_accessor :environment
      attr_accessor :environments
    end
  end
end
