# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CalculatorService
  # Add Model.
  class Add < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :a

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :b

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['a'] = 'a'
      @_hash['b'] = 'b'
      @_hash
    end

    def initialize(a = nil,
                   b = nil)
      @a = a
      @b = b
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      a = hash['a']
      b = hash['b']

      # Create object from extracted values.
      Add.new(a,
              b)
    end
  end
end
