# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CalculatorService
  # ICalculatorAddInputMessage Model.
  class ICalculatorAddInputMessage < BaseModel
    # TODO: Write general description for this method
    # @return [Add]
    attr_accessor :parameters

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['parameters'] = 'parameters'
      @_hash
    end

    def initialize(parameters = nil)
      @parameters = parameters
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      parameters = Add.from_hash(hash['parameters']) if hash['parameters']

      # Create object from extracted values.
      ICalculatorAddInputMessage.new(parameters)
    end
  end
end
