# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CalculatorService
  # SubtractResponse Model.
  class SubtractResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :result

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['result'] = 'result'
      @_hash
    end

    def initialize(result = nil)
      @result = result
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      result = hash['result']

      # Create object from extracted values.
      SubtractResponse.new(result)
    end
  end
end
